### ISSUE TITLE
libcint: use Julia Artifact libcint_jll.jl

### ISSUE THREAD

**Issue by carstenbauer** [FermiQC/Fermi.jl#111]
Have you considered using https://github.com/JuliaBinaryWrappers/libcint_jll.jl instead of manually downloading and compiling libcint in `deps/builds.jl`?

Using a custom `deps/build.jl` isn't the recommended approach for distributing binary dependencies anymore. Using Julia's artifact system is much cleaner.

**Comment by gustavojra** [comment]
Hi Carsten,

Thanks for commenting on this particular part of the code. I, admittedly, got it to work and moved on to the next thing, so some revision to it is very welcome.

We were using `JuliaBinaryWrappers` on a previous version of Fermi because our backend for integrals was libint2, you can still find that work in the package [Lints.jl](https://github.com/FermiQC/Lints.jl).

Finally, and I am sorry about this, we are working on a factorization that puts atomic integrals in a separated package, see [GaussianBasis.jl](https://github.com/FermiQC/GaussianBasis.jl). This is done so that people looking for a simple integral library wrap can use `GaussianBasis.jl` instead of Fermi. Moreover, it compartmentalized the code so there are no "external" libraries or build step in Fermi itself (thou that is solved by `libcint_jll.jl` as well).

Anyway, I am going to bring this factorization in by the end of the week. I may copy your work over to `GaussianBasis.jl` or you can submit a PR there (preferable to credit you). 

Thank you again for playing with Fermi.
